name: std_dev_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^1.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/gif/
